[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "python3", "pip"]

[phases.build]
cmds = [
  "npm install",
  "pip3 install yt-dlp",
  "ln -sf $(which yt-dlp) /usr/local/bin/yt-dlp || true"
]

[start]
cmd = "node server.js"

