[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "wget"]

[phases.build]
cmds = [
  "npm install",
  "wget -q https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp",
  "chmod a+rx /usr/local/bin/yt-dlp"
]

[start]
cmd = "node server.js"

